
class General:
    botAvatarURL =          "https://i.imgur.com/8PqN7yq.jpg"
    botInviteURL =          "https://discord.com/oauth2/authorize?client_id=768309916112650321&scope=bot&permissions=474311750"
    botInviteURLAdmin =     "https://discord.com/oauth2/authorize?client_id=768309916112650321&scope=bot&permissions=8"
    supportServerURL =      "https://discord.com/invite/AAJPHqNXUy"
    githubURL =             "https://github.com/Alex0622/Al3xis-Bot-dev"

class InfoCommands:
    about =             'Get information about the bot.'
    addrole =           'Add a role to a member.'
    ann =               'Make announcements.'
    announce =          'Make announcements.'
    announcement =      'Make announcements.'
    av =                'Get and post the avatar of the member mentioned.'
    avatar =            'Get and post the avatar of the member mentioned.'
    ban =               'Ban the member mentioned in the command. | Permanent ban.'
    bans =              "Fetch the bans of this server."
    calc =              'Basic calculator (add, subtract, multiply and divide two values).'
    calculator =        'Basic calculator (add, subtract, multiply and divide two values).'
    clear =             'Delete messsages. | Max messages per command: `500`.'
    dm =                'Send direct messages to users (usually to reply to their reports).'
    DM =                'Send direct messages to users (usually to reply to their reports).'
    embed =             'Send messages in embeds.'
    id =                'Get the ID of the given member.'
    ID =                'Get the ID of the given member.' 
    info =              'Get information about the bot.'
    inv =               'Invite the bot to your server or join our Discord server.'
    invite =            'Invite the bot to your server or join our Discord server.'
    h =                 'List all commands or get information for a single command/category.'
    help =              'List all commands or get information for a single command/category.'
    kick =              'Kick a member from the server.'
    latency =           "Shows the bot's latency/ping."
    logout =            "Disconnect the bot from Discord."
    mathrandom =        'Choose a random number between two values.'
    mathsq =            "Find the square of a number."
    mathsqrt =          "Find the square root of a number."
    membercount =       'Get how many members are in your server.'
    msg =               'Send direct messages to users.'
    mute =              'Mute members. | Duration: seconds, minutes, hours or days.'
    nick =              "Change or get a member's nickname on this guild."
    ping =              "Shows the bot's latency/ping."
    pm =                'Mute a member permanently.'
    pmute =             'Mute a member permanently.'
    pong =              "Shows the bot's latency/ping."
    purge =             'Delete messsages. | Max messages per command: `500`.'
    remind =            'Set a reminder. | Duration: seconds, minutes, hours or days.'
    reminder =          'Set a reminder. | Duration: seconds, minutes, hours or days.'
    removerole =        'Remove a role from a member.'
    report =            'Report bugs, errors or problems related to the bot.'
    ri =                'Get information about a role.'
    role =              'Get information about a role.'
    roleinfo =          'Get information about a role.'
    save =              'Save messages to the secret channel.'
    say =               'Send messages through the bot.'
    servericon =        'Show the server icon.'
    serverinfo =        'Get information about this server.'
    setnick =           "Change or get a member's nickname on this guild."
    si =                'Get information about this server.'
    softban =           'Ban and automatically unban a member.' 
    source =            "Get the bot's source code."
    sug =               'Make a new suggestion for the bot.'
    suggest =           'Make a new suggestion for the bot.'
    ui =                'Get information about a member.'
    unban =             'Remove ban from member.'
    unmute =            'Remove `Muted` role from member.'
    updatereport =      'Update the status of a report.'
    updatesuggestion =  'Update the status of a suggestion.'
    ur =                'Update the status of a report.'
    us =                'Update the status of a suggestion.'
    user =              'Get information about a member.'
    userinfo =          'Get information about a member.'
    voicemute =         'Mute a member in voice channels.'
    voiceunmute =       'Unmute a member in voice channels.'
    vote =              'Vote Al3xis on Discord bot lists!'

class UsageCommands:
    about =             '`a!about`'
    addrole =           '`a!addrole (role) (member)`'
    ann =               '`a!ann #channel (message)`'
    announce =          '`a!announce (#channel) (message)`'
    announcement =      '`a!announcement (#channel) (message)'
    av =                '`a!av (member)`'
    avatar =            '`a!avatar (member)`'
    ban =               '`a!ban (member) (reason)`'
    bans =              '`a!bans`'
    calc =              '`a!calc (value 1) (+ - / *) (value 2)`'
    calculator =        '`a!calculator (value 1) (+ - / *) (value 2)`' 
    clear =             '`a!clear (amount of messages that will be purged)`'
    dm =                '`a!dm (member) (message)`'
    DM =                '`a!DM (member) (message)`'
    embed =             '`a!embed (message)`'
    id =                '`a!id (member)`'
    ID =                '`a!ID (member)`'
    info =              '`a!info`'
    inv =               '`a!inv`'
    invite =            '`a!invite`'
    h =                 '`a!h (command/category)`'
    help =              '`a!help (command/category)`'
    kick =              '`a!kick (member) (reason)`'
    latency =           '`a!latency`'
    logout =            '`a!logout`'
    mathrandom =        '`a!mathrandom (value1) (value2)`'
    mathsq =            '`a!mathsq (value)`'
    mathsqrt =          '`a!mathsqrt (value)`'
    membercount =       '`a!membercount`'
    msg =               '`a!msg (member) (reason)`'
    mute =              '`a!mute (member) (duration) (reason)`'
    nick =              '`a!nick (member) (nickname/"remove") `'
    ping =              '`a!ping`'
    pm =                '`a!pm (member) (reason)`'
    pmute =             '`a!pmute (member) (reason)`'
    pong =              '`a!pong`'
    purge =             '`a!purge (amount of messages that will be purged)`'
    remind =            '`a!remind (time) (message)`'
    reminder =          '`a!reminder (time) (message)`'
    removerole =        '`a!removerole (role) (member)`'
    report =            '`a!report (message)`'
    ri =                '`a!ri (role)`'
    role =              '`a!role (role)`'
    roleinfo =          '`a!roleinfo (role)`'
    save =              '`a!save (message)`' 
    say =               '`a!say (message)`'
    servericon =        '`a!servericon`'
    serverinfo =        '`a!serverinfo`'
    setnick =           '`a!setnick (member) (nickname/"remove")`'
    si =                '`a!si`'
    softban =           '`a!softban (member) (reason)`'
    source =            '`a!source`'
    sug =               '`a!sug (suggestion)`' 
    suggest =           '`a!suggest (suggestion)`'
    ui =                '`a!ui (member)`'
    unban =             '`a!unban ID (reason)`'
    unmute =            '`a!unmute (member) (reason)`'
    updatereport =      '`a!updatereport (message ID) (comment)`'
    updatesuggestion =  '`a!updatesuggestion (message ID) (accept/deny/pending) (reason)`'
    ur =                '`a!ur (message ID) (comment)`'
    us =                '`a!us (message ID) (accept/deny/pending) (reason)`'
    user =              '`a!user (member)`'
    userinfo =          '`a!userinfo (member)`'
    voicemute =         '`a!voicemute (member) (reason)`'
    voiceunmute =       '`a!voiceunmute (member) (reason)`'
    vote =              '`a!vote`'    
    
class AliasesCommands:
    about =             'info'
    addrole =           'No aliases'
    ann =               'announce, announcement'
    announce =          'announcement, ann'
    announcement =      'ann, announce'
    av =                'avatar'
    avatar =            'av'
    ban =               'No aliases'
    bans =              'No aliases'
    calc =              'calculator'
    calculator =        'calc'
    clear =             'purge'
    dm =                'DM, msg'
    DM =                'dm, msg'
    embed =             'No aliases'
    id =                'ID'
    ID =                'id'
    info =              'No aliases'
    inv =               'invite'
    invite =            'inv'
    h =                 'help'
    help =              'h'
    kick =              'No aliases'
    latency =           'ping, pong'
    logout =            'No aliases'
    membercount =       'No aliases'
    mathrandom =        'No aliases'
    mathsq =            'No aliases'
    mathsqrt =          'No aliases'
    msg =               'dm, DM'
    mute =              'No aliases'
    nick =              'setnick'
    ping =              'pong, latency'
    pm =                'pmute'
    pmute =             'pm'
    purge =             'clear'
    pong =              'ping, latency'
    remind =            'reminder'
    reminder =          'remind'
    removerole =        'No aliases'
    report =            'No aliases'
    ri =                'role, roleinfo'
    role =              'ri, roleinfo'
    roleinfo =          'ri, role'
    save =              'No aliases'
    say =               'No aliases'
    servericon =        'No aliases'
    serverinfo =        'si'
    setnick =           'nick'
    si =                'serverinfo'
    softban =           'No aliases'
    source =            'No aliases'
    sug =               'suggest'
    suggest =           'sug'
    ui =                'user, userinfo'
    unban =             'No aliases'
    unmute =            'No aliases'
    updatereport =      'ur'
    updatesuggestion =  'us'
    ur =                'updatereport'
    us =                'updatesuggestion'
    user =              'ui, userinfo'
    userinfo =          'ui, user'
    voicemute =         'No aliases'
    voiceunmute =       'No aliases'
    vote =              'No aliases'

class RequiredPermissions:
    about =             'NO REQUIRED PERMISSION'
    addrole =           'MANAGE ROLES'
    ann =               'ADMINISTRATOR'
    announce =          'ADMINISTRATOR'
    announcement =      'ADMINISTRATOR'
    av =                'NO REQUIRED PERMISSION'
    avatar =            'NO REQUIRED PERMISSION'
    ban =               'BAN MEMBERS'
    bans =              'BAN MEMBERS'
    calc =              'NO REQUIRED PERMISSION'
    calculator =        'NO REQUIRED PERMISSION'
    clear =             'MANAGE MESSAGES'
    dm =                "Bot's owner"
    DM =                "Bot's owner"
    embed =             "NO REQUIRED PERMISSION"
    id =                'NO REQUIRED PERMISSION'
    ID =                'NO REQUIRED PERMISSION'
    info =              'NO REQUIRED PERMISSION'
    inv =               'NO REQUIRED PERMISSION'
    invite =            'NO REQUIRED PERMISSION'
    h =                 'NO REQUIRED PERMISSION'
    help =              'NO REQUIRED PERMISSION'
    kick =              'BAN MEMBERS'
    latency =           'NO REQUIRED PERMISSION'
    logout =            "Bot's owner"
    mathrandom =        'NO REQUIRED PERMISSION'
    mathsq =            'NO REQUIRED PERMISSION'
    mathsqrt =          'NO REQUIRED PERMISSION'
    membercount =       'NO REQUIRED PERMISSION'
    msg =               "Bot's owner"
    mute =              'BAN MEMBERS'
    nick =              'MANAGE NICKNAMES'
    ping =              'NO REQUIRED PERMISSION'
    pm =                'BAN MEMBERS'
    pmute =             'BAN MEMBERS'
    purge =             'MANAGE MESSAGES'
    pong =              'NO REQUIRED PERMISSION'
    remind =            'NO REQUIRED PERMISSION'
    reminder =          'NO REQUIRED PERMISSION'
    removerole =        'NO REQUIRED PERMISSION'
    report =            'NO REQUIRED PERMISSION'
    ri =                'NO REQUIRED PERMISSION'
    role =              'NO REQUIRED PERMISSION'
    roleinfo =          'NO REQUIRED PERMISSION'
    save =              "BOT'S OWNER"
    say =               'NO REQUIRED PERMISSION'
    servericon =        'NO REQUIRED PERMISSION'
    serverinfo =        'NO REQUIRED PERMISSION'
    setnick =           'MANAGE NICKNAMES'
    si =                'NO REQUIRED PERMISSION'
    softban =           'BAN MEMBERS'
    source =            'NO REQUIRED PERMISSION'
    sug =               'NO REQUIRED PERMISSION'
    suggest =           'NO REQUIRED PERMISSION'
    ui =                'NO REQUIRED PERMISSION'
    unban =             'BAN MEMBERS'
    unmute =            'BAN MEMBERS'
    updatereport =      "Bot's owner"
    updatesuggestion =  "Bot's owner"
    ur =                "Bot's owner"
    us =                "Bot's owner"
    user =              'NO REQUIRED PERMISSION'
    userinfo =          'NO REQUIRED PERMISSION'
    voicemute =         'NO REQUIRED PERMISSION'
    voiceunmute =       'NO REQUIRED PERMISSION'
    vote =              'NO REQUIRED PERMISSION'

class Channels:
    suggestionsChannel =    793989328602791946
    chatChannel =           821782500375265281
    botChannel =            822135281511694386
    joinsleavesChannel =    832320231325696070
    ownerChannel =          793989996494192692
    logChannel =            793990292213727262
    commandsChannel =       826133121573191681
    reportsChannel =        826158056173469727
    logCommandsChannel =    826133121573191681
    DMsChannel =            830496524530221067
    logErrorsChannel =      857408961837924383

class Colors:
    red =               0xde0707
    lightBlue =         0x32d9cb
    green =             0x6cfd00
    blue =              0x0037fa
    yellow =            0xf1fc14 
    orange =            0xe07007
    purple =            0x8a1bba
    darkGreen =         0x156109
    gray =              0x678188

class Emojis:
    ballotBoxWithCheck =        '☑️'
    x =                         '❌'
    warning =                   '⚠️'
    noEntry =                   '⛔'
    whiteCheckMark =            '✅'
    octagonalSign =             '🛑'
    eyes =                      '👀'
    wave =                      '👋'
    loading =                   '<a:loading:882124504451653652>'

BadWords = ["bitch","fuck","nigg","shit"]